### ISSUE TITLE
laggy output

### ISSUE THREAD

**Issue by Nughu** [Nootna8/Beats2Fun#16]
I got it working, but the result video has audio and video lags the whole time :(

**Comment by Nootna8** [comment]
You're using the latest commit or the latest windows release?

**Comment by Nootna8** [comment]
Also is it lagging the whole time or just the video transitions?

**Comment by Nughu** [comment]
I'm on Windows. I think the lagging is at every transition, yes. I have given only FHD videos with 25fps and set the same in Beats2Fun.

**Comment by Nootna8** [comment]
I mean did you clone the latest commit and run python yourself, or have did you just download and run set the setup. Cuz the latest setup is still missing a bunch of fixes

**Comment by Nughu** [comment]
Yeah I used the setup. I'll try the other way now, thanks for reaching out!

**Comment by Nootna8** [comment]
Might have the same problem, been a while since I worked on this. Reason would probably be I used h264 concat for a huuge speed boost instead of reencoding. Let me know your findings, changing to reencoding anyway shouldn't be a big issue

**Comment by Nughu** [comment]
Okay I had to install attrdict separately before requirements.txt. But it's still crashing, with this error: 

> J:\Pr0n\Video\Funscript\Beats2Fun>pip install -r requirements.txt --no-cache-dir
Collecting colour (from -r requirements.txt (line 1))
  Downloading colour-0.1.5-py2.py3-none-any.whl (23 kB)
Collecting Gooey (from -r requirements.txt (line 2))
  Downloading Gooey-1.0.8.1-py2.py3-none-any.whl (680 kB)
     ---------------------------------------- 680.5/680.5 kB 10.8 MB/s eta 0:00:00
Collecting halo (from -r requirements.txt (line 3))
  Downloading halo-0.0.31.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Collecting matplotlib (from -r requirements.txt (line 4))
  Downloading matplotlib-3.7.1-cp311-cp311-win_amd64.whl (7.6 MB)
     ---------------------------------------- 7.6/7.6 MB 13.2 MB/s eta 0:00:00
Collecting pydub (from -r requirements.txt (line 5))
  Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Collecting simfile (from -r requirements.txt (line 6))
  Downloading simfile-2.1.1-py3-none-any.whl (42 kB)
     ---------------------------------------- 42.2/42.2 kB ? eta 0:00:00
Requirement already satisfied: tqdm in c:\python311\lib\site-packages (from -r requirements.txt (line 7)) (4.65.0)
Requirement already satisfied: platformdirs in c:\python311\lib\site-packages (from -r requirements.txt (line 8)) (3.2.0)
Requirement already satisfied: Pillow>=4.3.0 in c:\python311\lib\site-packages (from Gooey->-r requirements.txt (line 2)) (9.5.0)
Requirement already satisfied: psutil>=5.4.2 in c:\python311\lib\site-packages (from Gooey->-r requirements.txt (line 2)) (5.9.5)
Collecting colored>=1.3.93 (from Gooey->-r requirements.txt (line 2))
  Downloading colored-1.4.4.tar.gz (36 kB)
  Preparing metadata (setup.py) ... done
Collecting pygtrie>=2.3.3 (from Gooey->-r requirements.txt (line 2))
  Downloading pygtrie-2.5.0-py3-none-any.whl (25 kB)
Collecting wxpython>=4.1.0 (from Gooey->-r requirements.txt (line 2))
  Downloading wxPython-4.2.0.tar.gz (71.0 MB)
     ---------------------------------------- 71.0/71.0 MB 13.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-ooftjjxb\wxpython_86bb6a563582476c83b73ab465820118\setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-ooftjjxb\wxpython_86bb6a563582476c83b73ab465820118\buildtools\config.py", line 30, in <module>
          from attrdict import AttrDict
        File "C:\Python311\Lib\site-packages\attrdict\__init__.py", line 5, in <module>
          from attrdict.mapping import AttrMap
        File "C:\Python311\Lib\site-packages\attrdict\mapping.py", line 4, in <module>
          from collections import Mapping
      ImportError: cannot import name 'Mapping' from 'collections' (C:\Python311\Lib\collections\__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


...any idea what I'm missing?
